# path
dataset_original_path: /root/ml_process_feb23/data/raw/AER_credit_card_data.csv
dataset_output_df_path: /root/ml_process_feb23/data/processed/output_df.pkl
dataset_input_df_path: /root/ml_process_feb23/data/processed/input_df.pkl
dataset_train_path: 
- /root/ml_process_feb23/data/processed/x_train.pkl
- /root/ml_process_feb23/data/processed/y_train.pkl
dataset_valid_path: 
- /root/ml_process_feb23/data/processed/x_valid.pkl
- /root/ml_process_feb23/data/processed/y_valid.pkl
dataset_test_path: 
- /root/ml_process_feb23/data/processed/x_test.pkl
- /root/ml_process_feb23/data/processed/y_test.pkl
dataset_EDA_path: /root/ml_process_feb23/data/processed/EDA_df.pkl
dataset_modelling_path: 
- /root/ml_process_feb23/data/processed/df_train.pkl
- /root/ml_process_feb23/data/processed/df_valid.pkl
- /root/ml_process_feb23/data/processed/df_test.pkl
dataset_train_balanced_path: 
- /root/ml_process_feb23/data/processed/x_train_rus.pkl
- /root/ml_process_feb23/data/processed/y_train_rus.pkl
- /root/ml_process_feb23/data/processed/x_train_ros.pkl
- /root/ml_process_feb23/data/processed/y_train_ros.pkl
- /root/ml_process_feb23/data/processed/x_train_smote.pkl
- /root/ml_process_feb23/data/processed/y_train_smote.pkl
training_log_path:
- /root/ml_process_feb23/logs/training_log_baseline.json
- /root/ml_process_feb23/logs/training_log_alternative.json
- /root/ml_process_feb23/logs/training_log_tuned.json
production_model_path: /root/ml_process_feb23/models/best_model.pkl

# Debug related
print_debug: True

# columns by data type related
object_columns:
- card
- owner
- selfemp
float_columns:
- age
- income
- share
- expenditure
int_columns:
- reports
- dependents
- months
- majorcards
- active


# columns by dependency related
target:
- card
predictors:
- reports
- age
- income
- share
- expenditure
- owner
- selfemp
- dependents
- months
- majorcards
- active

# Range of data related
range_reports:
- 0
- 15
range_age:
- 18
- 99
range_income:
- 0
- 150000
range_share:
- 0
- 100
range_expenditure:
- 0
- 5000
range_dependents:
- 0
- 6
range_months:
- 0
- 600
range_majorcards:
- 0
- 1
range_active:
- 0
- 50
range_owner:
- 'yes'
- 'no'
range_selfemp:
- 'yes'
- 'no'
range_card: 
- 'yes'
- 'no'

# Group of features/parameters for preprocessing related
datasets:
- df_train
- df_valid
- df_test
cols_to_log:
- income
- expenditure
- months
log_cols:
- income_log
- expenditure_log
- months_log
num_columns:
- reports
- age
- income_log
- share
- expenditure_log
- dependents
- months_log
- majorcards
- active
cat_columns:
- owner
- selfemp
- card
bins_age:
- 18
- 24
- 40
- 56
- 75
- 99
labels_age:
- 1
- 2
- 3
- 4
- 5
bins_reports:
- 0
- .99
- 2
- 14
labels_reports:
- 0
- 1
- 2
bins_dependents:
- 0
- 0.99
- 1.99
- 3
- 6
labels_dependents:
- 0
- 1
- 2
- 3
bins_active:
- 0
- 0.99
- 4
- 6
- 46
labels_active:
- 0
- 1
- 2
- 3

# Group of features/parameters for modelling related
binned_cols:
- age_bin
- reports_bin
- dependents_bin
- active_bin
original_cols:
- age
- reports
- dependents
- active

# Group of features/parameters for api related
predictors_api:
- owner
- selfemp
- reports
- age
- dependents
- months
- majorcards
- active
- income
- share
- expenditure
